namespace: faucet
commonLabels:
  namespace: faucet
patches:
- path: deployment.yaml
  target:
    kind: Deployment
resources:
- ../base
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: public.ecr.aws/x2t8a1o3/aleph-faucet-frontend
  newTag: latest