apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet-backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: faucet-backend
  template:
    metadata:
      labels:
        app: faucet-backend
    spec:
      restartPolicy: Always
      containers:
      - name: faucet-backend
        image: "public.ecr.aws/x2t8a1o3/aleph-faucet-backend:latest"
        imagePullPolicy: "Always"
        ports:
        - name: backend
          containerPort: 5555
        volumeMounts:
        - name: faucet-env-file
          mountPath: /backend/.env
          subPath: .env
        resources:
          requests:
            memory: "2500Mi"
            cpu: "1500m"
        livenessProbe:
          tcpSocket:
            port: 5555
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 5555
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
      serviceAccountName: faucet-app
      volumes:
      - name: faucet-env-file
        secret:
          secretName: env-file
          items:
          - key: .env
            path: .env