apiVersion: v1
kind: Service
metadata:
  name: faucet-backend
  labels:
    app: faucet-backend
spec:
  type: NodePort
  ports:
    - name: backend
      port: 5555
      targetPort: 5555
  selector:
    app: faucet-backend