apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: faucet-frontend
  template:
    metadata:
      labels:
        app: faucet-frontend
    spec:
      restartPolicy: Always
      containers:
      - name: faucet-frontend
        image: "public.ecr.aws/x2t8a1o3/aleph-faucet-frontend:latest"
        imagePullPolicy: "Always"
        ports:
        - name: frontend
          containerPort: 5556
        volumeMounts:
        - name: faucet-env-file
          mountPath: /frontend/.env
          subPath: .env
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 5556
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 5556
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
      serviceAccountName: faucet-app
      volumes:
      - name: faucet-env-file
        secret:
          secretName: env-file
          items:
          - key: .env
            path: .env